var Brule = new Object();

Brule.resources = {
    
}

Brule.enStrings = {
	Title: "CapitalTour",
	Home: "Home",
	Map: "Map",
	Me:"Me",
	About: "About",
	Topics: "Topics",
	Perspectives: "Another Perspective",
	Updatemsg: "There is a new version of CapitalTour available. Please visit your App Store",
	Offlinemap: "Please connect your phone to the internet to see the map.",
	Share_success: "Your content has been shared",
	Show_all: "Show All",
	Current_tour: "My Current Tour",
	My_bookmarks: "My Bookmarks",
	Settings: "Settings",
	Filter: "Filter",
	BB_remote_connect: "This app requires an internet connection to view images",
	Droid_remote_connect: "This media requires a remote connection to view. Please connect to wifi or cellular data",
	Droid_old_OS: "This media requires Android 2.3 or higher to play",
	Media_gallery: "Media gallery",
	Photos: "Photos",
	Video: "Video",
	Audio: "Audio",
	Close: "Close",
	Share: "Share",
	Geolocation: "Geolocation",
	Next_wpt: "Next Waypoint",
	Enable_geo_title: "Location Services Disabled",
	Enable_geo_message: "Please enable location services and internet connectivity for this feature",
	Topic_all: "All",
	Topic_none: "None",
	ToCs: "Terms and Conditions",
	Share_URL_dest: "http://www.canadascapital.gc.ca/mobile",
	Accessible_map: "Accessible map",
	Offer_survey: "Thank you for using our app! Would you be willing to take our survey?",
	Yes: "Yes",
	No: "No",
	Far_wps: "Waypoints in grey may be outside the area associated with your time selection.",
	Share_fb: "Post to Facebook",
	Share_tw: "Post to Twitter",
	Cancel: "Cancel",
	Survey_URL: "http://fluidsurveys.com/surveys/ncc-ccn/capital-tour-app/langeng/"
}

Brule.frStrings = {
	Title: "TourCapitale",
    Home: "Accueil",
    Map: "Carte",
    Me:"Moi",
    About: "À propos",
    Topics: "Sujets",
    Perspectives: "Autre point de vue",
    Updatemsg: "Une nouvelle version des Visites de la capitale est disponible. Veuillez visiter votre boutique d'applications.",
    Offlinemap: "Veuillez connecter votre t&eacute;l&eacute;phone &agrave; Internet pour voir la carte.",
    Share_success: "Votre contenu a &eacute;t&eacute; partag&eacute;",
    Show_all: "Tout montrer",
    Current_tour: "Ma visite en cours",
    My_bookmarks: "Mes signets",
    Settings: "Param&egrave;tres",
    Filter: "Filtre",
	BB_remote_connect: "This app requires an internet connection to view images",
	Droid_remote_connect: "This media requires a remote connection to view. Please connect to wifi or cellular data",
	Droid_old_OS: "This media requires Android 2.3 or higher to play",
	Media_gallery: "Media gallery",
	Photos: "Photos",
	Video: "Vid&eacute;o",
	Audio: "Audio",
	Close: "Fermer",
	Share: "Partager",
	Geolocation: "G&eacute;olocalisation",
	Next_wpt: "Prochain point d'int&eacute;r&ecirc;t",
	Enable_geo_title: "Location Services Disabled",
	Enable_geo_message: "Please enable location services and internet connectivity for this feature",
	Topic_all: "Tous",
	Topic_none: "Aucun",
	ToCs: "Conditions",
	Share_URL_dest: "http://www.capitaleducanada.gc.ca/mobile",
	Accessible_map: "Carte accessible",
	Offer_survey: "Merci d'avoir utilis&eacute; notre application! Voudriez-vous r&eacute;pondre &agrave; notre sondage?",
	Yes: "Oui",
	No: "Non",
	Far_wps: "Les points d'int&eacute;r&ecirc;t en gris peuvent se trouver &agrave; l'ext&eacute;rieur de la zone associ&eacute;e &agrave; la dur&eacute;e de la visite que vous avez choisie.",
	Share_fb: "Afficher sur Facebook",
	Share_tw: "Afficher sur Twitter",
	Cancel: "Annuler",
	Survey_URL: "http://fluidsurveys.com/surveys/ncc-ccn/capital-tour-app/langfra/"
}